# Generated by Django 3.2.5 on 2021-07-21 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shape', models.CharField(max_length=15)),
                ('node1x', models.CharField(max_length=15)),
                ('node1y', models.CharField(max_length=15)),
                ('node1z', models.CharField(max_length=15)),
                ('node2x', models.CharField(max_length=15)),
                ('node2y', models.CharField(max_length=15)),
                ('node2z', models.CharField(max_length=15)),
                ('designed', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
