# Generated by Django 3.2.5 on 2021-07-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='designed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='node1x',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
        migrations.AlterField(
            model_name='member',
            name='node1y',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
        migrations.AlterField(
            model_name='member',
            name='node1z',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
        migrations.AlterField(
            model_name='member',
            name='node2x',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
        migrations.AlterField(
            model_name='member',
            name='node2y',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
        migrations.AlterField(
            model_name='member',
            name='node2z',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
        migrations.AlterField(
            model_name='member',
            name='shape',
            field=models.CharField(max_length=25),
        ),
    ]
