# Generated by Django 3.2.5 on 2022-01-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20210721_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.IntegerField(default=1)),
                ('x', models.DecimalField(decimal_places=10, max_digits=14)),
                ('y', models.DecimalField(decimal_places=10, max_digits=14)),
                ('z', models.DecimalField(decimal_places=10, max_digits=14)),
            ],
        ),
    ]
