# Generated by Django 3.2.5 on 2022-01-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20220111_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='node1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='node1', to='model.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='node2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='node2', to='model.node'),
            preserve_default=False,
        ),
    ]
